// integrations/react/src/plugin/PluginsProvider.tsx
import React, { useMemo } from "react";

import { PluginsContext, PluginsContextValue } from "./PluginsContext";

interface PluginsProviderProps {
  plugins: PluginsContextValue;
  children: React.ReactNode;
}
export const PluginsProvider: React.FC<PluginsProviderProps> = ({
  plugins,
  children,
}) => (
  <PluginsContext.Provider value={plugins}>{children}</PluginsContext.Provider>
);

// integrations/solid/src/__internal__/plugins/PluginsProvider.tsx
import type { Component, JSXElement } from "solid-js";
import { createContext } from "solid-js";

import type { StackflowSolidPlugin } from "../StackflowSolidPlugin";

export type PluginsContextValue = Array<ReturnType<StackflowSolidPlugin>>;
export const PluginsContext = createContext<PluginsContextValue>(null as any);

interface PluginsProviderProps {
  children: JSXElement;
  value: PluginsContextValue;
}
export const PluginsProvider: Component<PluginsProviderProps> = (props) => (
  <PluginsContext.Provider value={props.value}>
    {props.children}
  </PluginsContext.Provider>
);
