// integrations/react/src/plugins/PluginsProvider.tsx
import React, { createContext } from "react";

import type { StackflowReactPlugin } from "../StackflowReactPlugin";

export type PluginsContextValue = Array<ReturnType<StackflowReactPlugin>>;
export const PluginsContext = createContext<PluginsContextValue>(null as any);

interface PluginsProviderProps {
  children: React.ReactNode;
  value: PluginsContextValue;
}
export const PluginsProvider: React.FC<PluginsProviderProps> = ({
  children,
  value,
}) => (
  <PluginsContext.Provider value={value}>{children}</PluginsContext.Provider>
);

// integrations/solid/src/__internal__/plugins/PluginsProvider.tsx
import type { Component, JSXElement } from "solid-js";
import { createContext } from "solid-js";

import type { StackflowSolidPlugin } from "../StackflowSolidPlugin";

export type PluginsContextValue = Array<ReturnType<StackflowSolidPlugin>>;
export const PluginsContext = createContext<PluginsContextValue>(null as any);

interface PluginsProviderProps {
  children: JSXElement;
  value: PluginsContextValue;
}
export const PluginsProvider: Component<PluginsProviderProps> = (props) => (
  <PluginsContext.Provider value={props.value}>
    {props.children}
  </PluginsContext.Provider>
);
