// demo/src/components/FeedCard.tsx
import React from "react";
import { LazyLoadImage } from "react-lazy-load-image-component";

import { useFlow } from "../useFlow";
import * as css from "./FeedCard.css";

interface FeedCardProps {
  articleId: string;
  title: string;
  region: string;
  price: number;
  daysAgo: number;
}
const FeedCard: React.FC<FeedCardProps> = ({
  articleId,
  title,
  price,
  region,
  daysAgo,
}) => {
  const { push } = useFlow();

  const imageUrl = `https://picsum.photos/800/800/?id=${articleId}`;

  const onClick = () => {
    push("Article", {
      articleId: String(articleId),
      title,
    });
  };

  return (
    <div className={css.container}>
      <button type="button" className={css.button} onClick={onClick}>
        <div className={css.thumbnail}>
          <LazyLoadImage
            src={imageUrl}
            effect="opacity"
            width={108}
            height={108}
          />
        </div>
        <div className={css.right}>
          <div className={css.title}>{title}</div>
          <div className={css.subtitle}>
            {region} · {daysAgo} day ago
          </div>
          <div className={css.price}>£{price}.00</div>
        </div>
      </button>
    </div>
  );
};

export default FeedCard;

// demo-solid/src/components/FeedCard.tsx
import { type Component, createMemo } from "solid-js";
import { useFlow } from "../useFlow";
import * as css from "./FeedCard.css";

interface FeedCardProps {
  articleId: string;
  title: string;
  region: string;
  price: number;
  daysAgo: number;
}
const FeedCard: Component<FeedCardProps> = (props) => {
  const { push } = useFlow();

  const imageUrl = createMemo(
    () => `https://picsum.photos/800/800/?id=${props.articleId}`,
  );

  const onClick = () => {
    push("Article", {
      articleId: String(props.articleId),
      title: props.title,
    });
  };

  return (
    <div class={css.container}>
      <button type="button" class={css.button} onClick={onClick}>
        <div class={css.thumbnail}>
          <img src={imageUrl()} alt={props.title} width={108} height={108} />
        </div>
        <div class={css.right}>
          <div class={css.title}>{props.title}</div>
          <div class={css.subtitle}>
            {props.region} · {props.daysAgo} day ago
          </div>
          <div class={css.price}>£{props.price}.00</div>
        </div>
      </button>
    </div>
  );
};

export default FeedCard;
