// integrations/react/src/__internal__/core/CoreProvider.tsx
import type { CoreStore, Stack } from "@stackflow/core";
import { createContext } from "react";

import { useDeferredValue, useSyncExternalStore } from "../shims";

export const CoreActionsContext = createContext<CoreStore["actions"]>(
  null as any,
);
export const CoreStateContext = createContext<Stack>(null as any);
export const CoreSubscribeContext = createContext<CoreStore["subscribe"]>(
  null as any,
);

export interface CoreProviderProps {
  coreStore: CoreStore;
  children: React.ReactNode;
}
export const CoreProvider: React.FC<CoreProviderProps> = ({
  coreStore,
  children,
}) => {
  const stack = useSyncExternalStore(
    coreStore.subscribe,
    coreStore.actions.getStack,
    coreStore.actions.getStack,
  );

  const deferredStack = useDeferredValue(stack);

  return (
    <CoreStateContext.Provider value={deferredStack}>
      <CoreActionsContext.Provider value={coreStore.actions}>
        <CoreSubscribeContext.Provider value={coreStore.subscribe}>
          {children}
        </CoreSubscribeContext.Provider>
      </CoreActionsContext.Provider>
    </CoreStateContext.Provider>
  );
};

CoreProvider.displayName = "CoreProvider";

// integrations/solid/src/core/CoreProvider.tsx
import type { CoreStore, Stack } from "@stackflow/core";
import type { Accessor, Component, JSXElement } from "solid-js";
import { createContext, useTransition } from "solid-js";
import { createStore, reconcile } from "solid-js/store";

export const CoreActionsContext = createContext<Accessor<CoreStore["actions"]>>(
  null as any,
);
export const CoreStateContext = createContext<{
  stack: Stack;
  pending: Accessor<boolean>;
}>(null as any);

export interface CoreProviderProps {
  coreStore: CoreStore;
  children: JSXElement;
}
export const CoreProvider: Component<CoreProviderProps> = (props) => {
  const [stack, setStack] = createStore(props.coreStore.actions.getStack());
  const [pending, startTransition] = useTransition();

  props.coreStore.subscribe(() => {
    startTransition(() => {
      setStack(reconcile(props.coreStore.actions.getStack(), { merge: true }));
    });
  });

  return (
    <CoreStateContext.Provider value={{ stack, pending }}>
      <CoreActionsContext.Provider value={() => props.coreStore.actions}>
        {props.children}
      </CoreActionsContext.Provider>
    </CoreStateContext.Provider>
  );
};
