// extensions/plugin-basic-ui/src/solid/primitives/useMaxWidth.ts
import { createEffect, createSignal, onCleanup } from "solid-js";

import { listenResize } from "../../common/utils";

export function useMaxWidth(props: {
  outerRef: HTMLElement | undefined;
  innerRef: HTMLElement | undefined;
  enable: boolean;
}) {
  const [maxWidth, setMaxWidth] = createSignal<number | undefined>(undefined);

  createEffect(() => {
    const $outer = props.outerRef;
    const $inner = props.innerRef;

    if (!props.enable || !$outer || !$inner) return;

    const dispose = listenResize(() => {
      const screenWidth = $outer.clientWidth;

      const leftWidth = $inner.offsetLeft;
      const centerWidth = $inner.clientWidth;
      const rightWidth = screenWidth - leftWidth - centerWidth;

      const sideMargin = Math.max(leftWidth, rightWidth);

      setMaxWidth(screenWidth - 2 * sideMargin);
    });

    onCleanup(dispose);
  });

  return {
    maxWidth,
  };
}

// extensions/plugin-basic-ui/src/react/hooks/useMaxWidth.ts
import { useEffect, useState } from "react";

import { listenResize, noop } from "../../common/utils";

export function useMaxWidth({
  outerRef,
  innerRef,
  enable,
}: {
  outerRef: React.ForwardedRef<any>;
  innerRef: React.MutableRefObject<any>;
  enable: boolean;
}) {
  const [maxWidth, setMaxWidth] = useState<number | undefined>(undefined);

  useEffect(() => {
    const $outer = outerRef && "current" in outerRef && outerRef.current;
    const $inner = innerRef.current;

    if (!enable || !$outer || !$inner) {
      return noop;
    }

    const dispose = listenResize(() => {
      const screenWidth = $outer.clientWidth;

      const leftWidth = $inner.offsetLeft;
      const centerWidth = $inner.clientWidth;
      const rightWidth = screenWidth - leftWidth - centerWidth;

      const sideMargin = Math.max(leftWidth, rightWidth);

      setMaxWidth(screenWidth - 2 * sideMargin);
    });

    return dispose;
  });

  return {
    maxWidth,
  };
}
