// extensions/plugin-basic-ui/src/solid/components/AppBar.solid.tsx
/* @jsxImportSource solid-js */

import { useActions, useActivity } from "@stackflow/solid";
import { assignInlineVars } from "@vanilla-extract/dynamic";
import type { JSXElement } from "solid-js";
import { Match, Show, Switch, createMemo, mergeProps } from "solid-js";

import { useAppBarTitleMaxWidth } from "@stackflow/solid-ui-core";
import { IconBack, IconClose } from "../../common/assets";
import type { GlobalVars } from "../../common/basicUIPlugin.css";
import { globalVars } from "../../common/basicUIPlugin.css";
import { useGlobalOptions } from "../basicUIPlugin.solid";

import * as css from "../../common/components/AppBar.css";
import * as appScreenCss from "../../common/components/AppScreen.css";
import { compactMap } from "../../common/utils";

type AppBarProps = Partial<
  Pick<
    GlobalVars["appBar"],
    | "borderColor"
    | "borderColorTransitionDuration"
    | "borderSize"
    | "height"
    | "heightTransitionDuration"
    | "overflow"
    | "iconColor"
    | "iconColorTransitionDuration"
    | "textColor"
    | "textColorTransitionDuration"
    | "backgroundColor"
    | "backgroundColorTransitionDuration"
  >
> & {
  ref?: HTMLDivElement;
  title?: JSXElement;
  renderLeft?: () => JSXElement;
  renderRight?: () => JSXElement;
  backButton?:
    | {
        renderIcon?: () => JSXElement;
        ariaLabel?: string;
        onClick?: (e: MouseEvent) => void;
      }
    | {
        render?: () => JSXElement;
      };
  closeButton?:
    | {
        renderIcon?: () => JSXElement;
        ariaLabel?: string;
        onClick?: (e: MouseEvent) => void;
      }
    | {
        render?: () => JSXElement;
      };
  closeButtonLocation?: "left" | "right";
  border?: boolean;
  modalPresentationStyle?: "fullScreen";
  activityEnterStyle?: "slideInLeft";
  onTopClick?: (e: MouseEvent) => void;
};
const AppBar = (_props: AppBarProps) => {
  const props = mergeProps(_props, {
    closeButtonLocation: "left",
    border: true,
  });
  const actions = useActions();
  const activity = useActivity();

  const globalOptions = useGlobalOptions();
  const globalCloseButton = globalOptions.appBar?.closeButton;
  const globalBackButton = globalOptions.appBar?.backButton;

  let centerRef: HTMLDivElement | undefined;

  const { maxWidth } = useAppBarTitleMaxWidth({
    outerRef: props.ref,
    innerRef: centerRef,
    enable: globalOptions.theme === "cupertino",
  });

  const onBackClick = (e: MouseEvent) => {
    if (
      props.backButton &&
      "onClick" in props.backButton &&
      props.backButton.onClick
    ) {
      props.backButton.onClick(e);
    }

    if (!e.defaultPrevented) {
      actions.pop();
    }
  };

  const BackButton = () => (
    <Show when={activity() && !activity()?.isRoot}>
      <Switch
        fallback={
          <button
            type="button"
            class={css.backButton}
            onClick={onBackClick}
            innerHTML={IconBack()}
          />
        }
      >
        <Match
          when={
            props.backButton &&
            "render" in props.backButton &&
            props.backButton.render
          }
        >
          {(render) => render()()}
        </Match>
        <Match
          when={
            globalBackButton &&
            "render" in globalBackButton &&
            globalBackButton.render
          }
        >
          {(render) => render()()}
        </Match>
        <Match when={props.backButton || globalBackButton}>
          <button
            type="button"
            class={css.backButton}
            aria-label={
              props.backButton && "ariaLabel" in props.backButton
                ? props.backButton.ariaLabel
                : globalBackButton && "ariaLabel" in globalBackButton
                  ? globalBackButton.ariaLabel
                  : undefined
            }
            onClick={onBackClick}
          >
            <Switch fallback={<div innerHTML={IconBack()} />}>
              <Match
                when={
                  props.backButton &&
                  "renderIcon" in props.backButton &&
                  props.backButton.renderIcon
                }
              >
                {(render) => render()()}
              </Match>
              <Match
                when={
                  globalBackButton &&
                  "renderIcon" in globalBackButton &&
                  globalBackButton.renderIcon
                }
              >
                {(render) => render()()}
              </Match>
              <Match when={props.modalPresentationStyle === "fullScreen"}>
                <div innerHTML={IconClose()} />
              </Match>
            </Switch>
          </button>
        </Match>
      </Switch>
    </Show>
  );

  const onCloseClick = (e: MouseEvent) => {
    if (
      props.closeButton &&
      "onClick" in props.closeButton &&
      props.closeButton.onClick
    ) {
      props.closeButton.onClick(e);
    }

    if (
      !e.defaultPrevented &&
      globalCloseButton &&
      "onClick" in globalCloseButton
    ) {
      globalCloseButton.onClick?.(e);
    }
  };

  const CloseButton = () => {
    const isRoot = createMemo(() => !activity() || !!activity()?.isRoot);

    const showCloseButton = (closeButton: AppBarProps["closeButton"]) =>
      (closeButton && "render" in closeButton && closeButton.render) ||
      (closeButton && "renderIcon" in closeButton && closeButton.renderIcon) ||
      (closeButton && "onClick" in closeButton && closeButton.onClick);

    return (
      <Show
        when={
          (showCloseButton(props.closeButton) ||
            showCloseButton(globalOptions.appBar?.closeButton)) &&
          isRoot()
        }
      >
        <Switch>
          <Match
            when={
              props.closeButton &&
              "render" in props.closeButton &&
              props.closeButton.render
            }
          >
            {(render) => render()()}
          </Match>
          <Match
            when={
              globalOptions.appBar?.closeButton &&
              "render" in globalOptions.appBar.closeButton &&
              globalOptions.appBar.closeButton.render
            }
          >
            {(render) => render()()}
          </Match>
          <Match when={true}>
            <button
              type="button"
              class={css.closeButton}
              aria-label={
                props.closeButton && "ariaLabel" in props.closeButton
                  ? props.closeButton.ariaLabel
                  : globalCloseButton && "ariaLabel" in globalCloseButton
                    ? globalCloseButton.ariaLabel
                    : undefined
              }
              onClick={onCloseClick}
            >
              <Switch fallback={<div innerHTML={IconClose()} />}>
                <Match
                  when={
                    props.closeButton &&
                    "renderIcon" in props.closeButton &&
                    props.closeButton.renderIcon
                  }
                >
                  {(render) => render()()}
                </Match>
                <Match
                  when={
                    globalOptions.appBar?.closeButton &&
                    "renderIcon" in globalOptions.appBar.closeButton &&
                    globalOptions.appBar.closeButton.renderIcon
                  }
                >
                  {(render) => render()()}
                </Match>
              </Switch>
            </button>
          </Match>
        </Switch>
      </Show>
    );
  };

  const hasLeft = createMemo(
    () =>
      !!(
        (props.closeButtonLocation === "left" && props.closeButton) ||
        props.backButton ||
        props.renderLeft
      ),
  );

  const closeButton = <CloseButton />;

  return (
    <div
      ref={props.ref}
      class={css.appBar({
        border: props.border,
        modalPresentationStyle: props.modalPresentationStyle,
        activityEnterStyle: props.activityEnterStyle,
      })}
      style={assignInlineVars(
        compactMap({
          [globalVars.appBar.iconColor]: props.iconColor,
          [globalVars.appBar.iconColorTransitionDuration]:
            props.iconColorTransitionDuration,
          [globalVars.appBar.textColor]: props.textColor,
          [globalVars.appBar.textColorTransitionDuration]:
            props.textColorTransitionDuration,
          [globalVars.appBar.borderColor]: props.borderColor,
          [globalVars.appBar.borderColorTransitionDuration]:
            props.borderColorTransitionDuration,
          [globalVars.appBar.borderSize]: props.borderSize,
          [globalVars.appBar.height]: props.height,
          [globalVars.appBar.heightTransitionDuration]:
            props.heightTransitionDuration,
          [globalVars.appBar.overflow]: props.overflow,
          [globalVars.appBar.backgroundColor]:
            props.backgroundColor || globalVars.backgroundColor,
          [globalVars.appBar.backgroundColorTransitionDuration]:
            props.backgroundColorTransitionDuration,
          [appScreenCss.vars.appBar.center.mainWidth]: `${maxWidth()}px`,
        }),
      )}
    >
      <div class={css.safeArea} />
      <div class={css.container}>
        <div class={css.left}>
          <Show when={props.closeButtonLocation === "left"}>{closeButton}</Show>
          <BackButton />
          {props.renderLeft?.()}
        </div>
        <div ref={centerRef} class={css.center}>
          <div
            class={css.centerMain({
              hasLeft: hasLeft(),
            })}
          >
            <Show when={typeof props.title === "string"} fallback={props.title}>
              <div class={css.centerText}>{props.title}</div>
            </Show>
            <button
              class={css.centerMainEdge}
              type="button"
              onClick={props.onTopClick}
            />
          </div>
        </div>
        <div class={css.right}>
          {props.renderRight?.()}
          <Show when={props.closeButtonLocation === "right"}>
            {closeButton}
          </Show>
        </div>
      </div>
    </div>
  );
};

export default AppBar;

// extensions/plugin-basic-ui/src/components/AppBar.tsx
import { useActions } from "@stackflow/react";
import {
  useActivityDataAttributes,
  useAppBarTitleMaxWidth,
  useMounted,
  useNullableActivity,
} from "@stackflow/react-ui-core";
import { assignInlineVars } from "@vanilla-extract/dynamic";
import clsx from "clsx";
import { forwardRef, useRef } from "react";
import { IconBack, IconClose } from "../assets";
import { useGlobalOptions } from "../basicUIPlugin";
import type { GlobalVars } from "../basicUIPlugin.css";
import { globalVars } from "../basicUIPlugin.css";
import { compactMap } from "../utils";
import * as css from "./AppBar.css";
import * as appScreenCss from "./AppScreen.css";

export type AppBarProps = Partial<
  Pick<
    GlobalVars["appBar"],
    | "borderColor"
    | "borderColorTransitionDuration"
    | "borderSize"
    | "height"
    | "heightTransitionDuration"
    | "overflow"
    | "iconColor"
    | "iconColorTransitionDuration"
    | "textColor"
    | "textColorTransitionDuration"
    | "backgroundColor"
    | "backgroundColorTransitionDuration"
    | "backgroundImage"
    | "backgroundImageTransitionDuration"
  >
> & {
  title?: React.ReactNode;
  renderLeft?: () => React.ReactNode;
  renderRight?: () => React.ReactNode;
  backButton?:
    | {
        renderIcon?: () => React.ReactNode;
        ariaLabel?: string;
        onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
      }
    | {
        render?: () => React.ReactNode;
      };
  closeButton?:
    | {
        renderIcon?: () => React.ReactNode;
        ariaLabel?: string;
        onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
      }
    | {
        render?: () => React.ReactNode;
      };
  closeButtonLocation?: "left" | "right";
  border?: boolean;
  modalPresentationStyle?: "fullScreen";
  activityEnterStyle?: "slideInLeft";
  onTopClick?: (e: React.MouseEvent) => void;
  enterStyle?: "cover";
  className?: string;
};
const AppBar = forwardRef<HTMLDivElement, AppBarProps>(
  (
    {
      title,
      renderLeft,
      renderRight,
      backButton,
      closeButton,
      closeButtonLocation = "left",
      border = true,
      modalPresentationStyle,
      activityEnterStyle,
      iconColor,
      iconColorTransitionDuration,
      textColor,
      textColorTransitionDuration,
      borderColor,
      borderColorTransitionDuration,
      borderSize,
      height,
      heightTransitionDuration,
      overflow,
      backgroundColor,
      backgroundColorTransitionDuration,
      backgroundImage,
      backgroundImageTransitionDuration,
      onTopClick,
      enterStyle,
      className,
    },
    ref,
  ) => {
    const actions = useActions();
    const activity = useNullableActivity();
    const activityDataAttributes = useActivityDataAttributes();

    const mounted = useMounted();

    const globalOptions = useGlobalOptions();
    const globalCloseButton = globalOptions.appBar?.closeButton;
    const globalBackButton = globalOptions.appBar?.backButton;

    const centerRef = useRef<any>(null);

    const { maxWidth } = useAppBarTitleMaxWidth({
      outerRef: ref,
      innerRef: centerRef,
      enable: globalOptions.theme === "cupertino",
    });

    const isUnderAppBarSlideTransition =
      ((globalOptions.theme === "cupertino" &&
        modalPresentationStyle !== "fullScreen") ||
        activityEnterStyle === "slideInLeft") &&
      enterStyle !== "cover";

    const onBackClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      if (backButton && "onClick" in backButton && backButton.onClick) {
        backButton.onClick(e);
      }

      if (!e.defaultPrevented) {
        actions.pop();
      }
    };

    const renderBackButton = () => {
      if (!activity) {
        return null;
      }
      if (activity.isRoot) {
        return null;
      }

      if (!backButton && !globalBackButton) {
        return (
          <button
            type="button"
            aria-label="Go Back"
            className={css.backButton}
            onClick={onBackClick}
          >
            <IconBack />
          </button>
        );
      }

      if (backButton && "render" in backButton && backButton.render) {
        return backButton.render?.();
      }
      if (
        globalBackButton &&
        "render" in globalBackButton &&
        globalBackButton.render
      ) {
        return globalBackButton.render?.();
      }

      return (
        <button
          type="button"
          className={css.backButton}
          aria-label={
            backButton && "ariaLabel" in backButton
              ? backButton.ariaLabel
              : globalBackButton && "ariaLabel" in globalBackButton
                ? globalBackButton.ariaLabel
                : undefined
          }
          onClick={onBackClick}
        >
          {(() => {
            if (
              backButton &&
              "renderIcon" in backButton &&
              backButton.renderIcon
            ) {
              return backButton.renderIcon();
            }
            if (
              globalBackButton &&
              "renderIcon" in globalBackButton &&
              globalBackButton.renderIcon
            ) {
              return globalBackButton.renderIcon();
            }

            if (modalPresentationStyle === "fullScreen") {
              return <IconClose />;
            }

            return <IconBack />;
          })()}
        </button>
      );
    };

    const onCloseClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      if (closeButton && "onClick" in closeButton && closeButton.onClick) {
        closeButton.onClick(e);
      }

      if (
        !e.defaultPrevented &&
        globalCloseButton &&
        "onClick" in globalCloseButton
      ) {
        globalCloseButton.onClick?.(e);
      }
    };

    const renderCloseButton = () => {
      const isRoot = !activity || activity.isRoot;

      const showCloseButton = (closeButton: AppBarProps["closeButton"]) =>
        (closeButton && "render" in closeButton && closeButton.render) ||
        (closeButton &&
          "renderIcon" in closeButton &&
          closeButton.renderIcon) ||
        (closeButton && "onClick" in closeButton && closeButton.onClick);

      if (
        !(
          showCloseButton(closeButton) ||
          showCloseButton(globalOptions.appBar?.closeButton)
        ) ||
        !isRoot
      ) {
        return null;
      }
      if (closeButton && "render" in closeButton && closeButton.render) {
        return closeButton.render();
      }
      if (
        globalCloseButton &&
        "render" in globalCloseButton &&
        globalCloseButton.render
      ) {
        return globalCloseButton.render();
      }

      return (
        <button
          type="button"
          className={css.closeButton}
          aria-label={
            closeButton && "ariaLabel" in closeButton
              ? closeButton.ariaLabel
              : globalCloseButton && "ariaLabel" in globalCloseButton
                ? globalCloseButton.ariaLabel
                : undefined
          }
          onClick={onCloseClick}
        >
          {(() => {
            if (
              closeButton &&
              "renderIcon" in closeButton &&
              closeButton.renderIcon
            ) {
              return closeButton.renderIcon();
            }
            if (
              globalCloseButton &&
              "renderIcon" in globalCloseButton &&
              globalCloseButton.renderIcon
            ) {
              return globalCloseButton.renderIcon();
            }

            return <IconClose />;
          })()}
        </button>
      );
    };

    return (
      <div
        ref={ref}
        className={clsx(
          css.appBar({
            border,
            modalPresentationStyle,
            activityEnterStyle,
            enterStyle,
          }),
          className,
        )}
        style={assignInlineVars(
          compactMap({
            [globalVars.appBar.iconColor]: iconColor,
            [globalVars.appBar.iconColorTransitionDuration]:
              iconColorTransitionDuration,
            [globalVars.appBar.textColor]: textColor,
            [globalVars.appBar.textColorTransitionDuration]:
              textColorTransitionDuration,
            [globalVars.appBar.borderColor]: borderColor,
            [globalVars.appBar.borderColorTransitionDuration]:
              borderColorTransitionDuration,
            [globalVars.appBar.borderSize]: borderSize,
            [globalVars.appBar.height]: height,
            [globalVars.appBar.heightTransitionDuration]:
              heightTransitionDuration,
            [globalVars.appBar.overflow]: overflow,
            [globalVars.appBar.backgroundColor]:
              backgroundColor ??
              (isUnderAppBarSlideTransition
                ? globalVars.backgroundColor
                : "transparent"),
            [globalVars.appBar.backgroundColorTransitionDuration]:
              backgroundColorTransitionDuration,
            [globalVars.appBar.backgroundImage]:
              backgroundImage ??
              (isUnderAppBarSlideTransition
                ? globalVars.appBar.backgroundImage
                : "none"),
            [globalVars.appBar.backgroundImageTransitionDuration]:
              backgroundImageTransitionDuration,
            [appScreenCss.vars.appBar.center.mainWidth]: `${maxWidth}px`,
          }),
        )}
        data-part="appBar"
        {...activityDataAttributes}
      >
        <div className={css.safeArea} />
        <div className={css.container}>
          <div className={css.left}>
            {closeButtonLocation === "left" && renderCloseButton()}
            {renderBackButton()}
            {renderLeft?.()}
          </div>
          <div ref={centerRef} className={css.center}>
            <div className={css.centerMain}>
              {typeof title === "string" ? (
                <div className={css.centerText}>{title}</div>
              ) : (
                title
              )}
              <button
                className={css.centerMainEdge}
                type="button"
                onClick={onTopClick}
              />
            </div>
          </div>
          <div className={css.right}>
            {renderRight?.()}
            {closeButtonLocation === "right" && renderCloseButton()}
          </div>
        </div>
      </div>
    );
  },
);

AppBar.displayName = "AppBar";

export default AppBar;
