// integrations/solid/src/__internal__/stack/StackProvider.tsx
import type { Stack } from "@stackflow/core";
import type { Accessor, Component, JSXElement } from "solid-js";
import { createContext } from "solid-js";

export const StackContext = createContext<Accessor<Stack>>(null as any);

interface StackProviderProps {
  children: JSXElement;
  value: Stack;
}
export const StackProvider: Component<StackProviderProps> = (props) => (
  <StackContext.Provider value={() => props.value}>
    {props.children}
  </StackContext.Provider>
);

// integrations/react/src/stack/StackProvider.tsx
import type { Stack } from "@stackflow/core";
import { createContext } from "react";

import { useMemoDeep } from "../utils";

export const StackContext = createContext<Stack>(null as any);

interface StackProviderProps {
  children: React.ReactNode;
  value: Stack;
}
export const StackProvider = ({ children, value }: StackProviderProps) => (
  <StackContext.Provider value={useMemoDeep(value)}>
    {children}
  </StackContext.Provider>
);

StackProvider.displayName = "StackProvider";
