// integrations/react/src/future/loader/useLoaderData.ts
import type { ActivityLoaderArgs } from "@stackflow/config";
import { use } from "react18-use";
import { useActivity } from "../../stable";

export function useLoaderData<
  T extends (args: ActivityLoaderArgs<any>) => any,
>(): Awaited<ReturnType<T>> {
  return use((useActivity().context as any)?.loaderData);
}

// integrations/solid/src/future/loader/useLoaderData.ts
import type { ActivityLoaderArgs } from "@stackflow/config";
import type { Accessor } from "solid-js";
import { useActivity } from "../../stable";

export function useLoaderData<
  T extends (args: ActivityLoaderArgs<any>) => any,
>(): Accessor<ReturnType<T>> {
  const activity = useActivity();
  return () => (activity()?.context as any)?.loaderData;
}
