// extensions/link/src/stable/solid/Link.solid.tsx
/** @jsxImportSource solid-js */

import type { UrlPatternOptions } from "@stackflow/plugin-history-sync/solid";
import { makeTemplate, useRoutes } from "@stackflow/plugin-history-sync/solid";
import { usePreloader } from "@stackflow/plugin-preload/solid";
import type { ActivityComponentType } from "@stackflow/solid";
import { useActions } from "@stackflow/solid";
import {
  type JSX,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
  splitProps,
} from "solid-js";

import { makeOnClick } from "../../common/makeOnClick";

export type AnchorProps = Omit<
  JSX.AnchorHTMLAttributes<HTMLAnchorElement>,
  "href" | "onClick"
>;

export type LinkProps<K, P> = {
  activityName: K;
  activityParams: P;
  animate?: boolean;
  replace?: boolean;
  urlPatternOptions?: UrlPatternOptions;
  onClick?: (
    e: MouseEvent & { currentTarget: HTMLAnchorElement; target: Element },
  ) => void;
} & AnchorProps;

export type TypeLink<T extends { [activityName: string]: unknown } = {}> = <
  K extends Extract<keyof T, string>,
>(
  props: LinkProps<K, T[K] extends ActivityComponentType<infer U> ? U : never>,
) => JSX.Element;

export const Link: TypeLink = (props) => {
  const [locals, others] = splitProps(props, [
    "ref",
    "children",

    // Custom Props
    "activityName",
    "activityParams",
    "animate",
    "replace",
    "urlPatternOptions",

    // Overriden Props
    "onClick",
  ]);

  const routes = useRoutes();
  const preloader = usePreloader({
    get urlPatternOptions() {
      return locals.urlPatternOptions;
    },
  });
  const actions = useActions();

  const [anchorRef, setAnchorRef] = createSignal<HTMLAnchorElement>();
  const [preloaded, setPreloaded] = createSignal(false);

  const match = createMemo(() =>
    routes.find((r) => r.activityName === locals.activityName),
  );
  const href = createMemo(() => {
    const m = match();

    if (!m) {
      return undefined;
    }

    const template = makeTemplate(m, locals.urlPatternOptions);
    const path = template.fill(locals.activityParams);

    return path;
  });

  createEffect(() => {
    const $anchor = anchorRef();

    if (preloaded() || !$anchor) {
      return;
    }

    const observer = new IntersectionObserver(([{ isIntersecting }]) => {
      if (isIntersecting) {
        preloader().preload(locals.activityName, locals.activityParams, {
          activityContext: {
            path: href(),
          },
        });
        setPreloaded(true);
      }
    });

    observer.observe($anchor);

    onCleanup(() => {
      observer.unobserve($anchor);
      observer.disconnect();
    });
  });

  const onClick = createMemo(() =>
    makeOnClick({
      activityName: locals.activityName,
      activityParams: locals.activityParams,
      actions,
      animate: locals.animate,
      replace: locals.replace,
      onClick: locals.onClick,
    }),
  );

  return (
    <a
      ref={(el) => {
        setAnchorRef(el);
        (locals.ref as ((el: HTMLAnchorElement) => void) | undefined)?.(el);
      }}
      href={href()}
      onClick={onClick()}
      draggable="false" // Disable long press behavior by default in iOS
      {...others}
    >
      {locals.children}
    </a>
  );
};

// extensions/link/src/stable/Link.tsx
import type { UrlPatternOptions } from "@stackflow/plugin-history-sync";
import { makeTemplate, useRoutes } from "@stackflow/plugin-history-sync";
import { usePreloader } from "@stackflow/plugin-preload";
import type { ActivityComponentType } from "@stackflow/react";
import { useActions } from "@stackflow/react";
import { forwardRef, useEffect, useMemo, useReducer, useRef } from "react";

import { mergeRefs } from "./mergeRefs";
import { omit } from "./omit";

export type AnchorProps = Omit<
  React.DetailedHTMLProps<
    React.AnchorHTMLAttributes<HTMLAnchorElement>,
    HTMLAnchorElement
  >,
  "ref" | "href"
>;

export type LinkProps<K, P> = {
  activityName: K;
  activityParams: P;
  animate?: boolean;
  replace?: boolean;
  urlPatternOptions?: UrlPatternOptions;
} & AnchorProps;

export type TypeLink<T extends { [activityName: string]: unknown } = {}> = <
  K extends Extract<keyof T, string>,
>(
  props: LinkProps<K, T[K] extends ActivityComponentType<infer U> ? U : never>,
) => React.ReactNode | null;

export const Link: TypeLink = forwardRef(
  (props, ref: React.ForwardedRef<HTMLAnchorElement>) => {
    const routes = useRoutes();
    const { preload } = usePreloader({
      urlPatternOptions: props.urlPatternOptions,
    });
    const { push, replace } = useActions();

    const anchorRef = useRef<HTMLAnchorElement>(null);
    const [preloaded, flagPreloaded] = useReducer(() => true, false);

    const href = useMemo(() => {
      const match = routes.find((r) => r.activityName === props.activityName);

      if (!match) {
        return undefined;
      }

      const template = makeTemplate(match, props.urlPatternOptions);
      const path = template.fill(props.activityParams);

      return path;
    }, [routes, props.activityName, props.activityParams]);

    useEffect(() => {
      if (preloaded || !anchorRef.current) {
        return () => {};
      }

      const $anchor = anchorRef.current;

      const observer = new IntersectionObserver(([{ isIntersecting }]) => {
        if (isIntersecting) {
          preload(props.activityName, props.activityParams, {
            activityContext: {
              path: href,
            },
          });
          flagPreloaded();
        }
      });

      observer.observe($anchor);

      return () => {
        observer.unobserve($anchor);
        observer.disconnect();
      };
    }, [anchorRef, flagPreloaded]);

    const anchorProps = omit(props, [
      // Custom Props
      "activityName",
      "activityParams",
      "animate",
      "replace",
      "urlPatternOptions",

      // Overriden Props
      "onClick",
    ]);

    const onClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
      if (props.onClick) {
        props.onClick(e);
      }

      if (
        (e.button === 0 &&
          !(e.currentTarget.target && e.currentTarget.target !== "_self")) ||
        (!e.defaultPrevented &&
          !e.metaKey &&
          !e.altKey && // triggers resource download
          !e.ctrlKey &&
          !e.shiftKey &&
          !(e.nativeEvent && e.nativeEvent.which === 2))
      ) {
        e.preventDefault();

        if (props.replace) {
          replace(
            props.activityName,
            props.activityParams,
            typeof props.animate === "undefined" || props.animate === null
              ? {}
              : { animate: props.animate },
          );
        } else {
          push(
            props.activityName,
            props.activityParams,
            typeof props.animate === "undefined" || props.animate === null
              ? {}
              : { animate: props.animate },
          );
        }
      }
    };

    return (
      <a
        ref={mergeRefs(ref, anchorRef)}
        href={href}
        onClick={onClick}
        draggable="false" // Disable long press behavior by default in iOS
        {...anchorProps}
      >
        {props.children}
      </a>
    );
  },
);

(Link as any).displayName = "Link";
