// integrations/solid/src/future/ActivityComponentType.tsx
import type {
  InferActivityParams,
  RegisteredActivityParamTypes,
} from "@stackflow/config";
import type { Component } from "solid-js";

export type ActivityComponentType<
  ActivityName extends Extract<keyof RegisteredActivityParamTypes, string>,
> = Component<{ params: InferActivityParams<ActivityName> }>;

// integrations/react/src/future/ActivityComponentType.tsx
import type {
  InferActivityParams,
  RegisteredActivityParamTypes,
} from "@stackflow/config";
import type React from "react";

export type ActivityComponentType<
  ActivityName extends Extract<keyof RegisteredActivityParamTypes, string>,
> = React.ComponentType<{ params: InferActivityParams<ActivityName> }>;
