// extensions/plugin-history-sync/src/solid/RoutesContext.solid.tsx
/* @jsxImportSource solid-js */

import type { JSXElement } from "solid-js";
import { createContext, useContext } from "solid-js";

import type { ActivityRoute } from "../common/ActivityRoute";

export const RoutesContext = createContext<ActivityRoute<unknown>[]>([]);

interface RoutesProviderProps<T> {
  routes: ActivityRoute<T>[];
  children: JSXElement;
}
export const RoutesProvider = <T,>(props: RoutesProviderProps<T>) => (
  <RoutesContext.Provider value={props.routes}>
    {props.children}
  </RoutesContext.Provider>
);

export function useRoutes() {
  return useContext(RoutesContext);
}

// extensions/plugin-history-sync/src/RoutesContext.tsx
import { createContext, useContext } from "react";

import type { ActivityRoute } from "./ActivityRoute";

export const RoutesContext = createContext<ActivityRoute<unknown>[]>([]);

interface RoutesProviderProps<T> {
  routes: ActivityRoute<T>[];
  children: React.ReactNode;
}
export const RoutesProvider = <T,>(props: RoutesProviderProps<T>) => (
  <RoutesContext.Provider value={props.routes as ActivityRoute<unknown>[]}>
    {props.children}
  </RoutesContext.Provider>
);

RoutesProvider.displayName = "RoutesProvider";

export function useRoutes() {
  return useContext(RoutesContext);
}
