// integrations/react/src/activity/ActivityProvider.tsx
import type { Activity } from "@stackflow/core";
import React, { createContext } from "react";

import { useMemoDeep } from "../utils";

export const ActivityContext = createContext<Activity>(null as any);

interface ActivityProviderProps {
  children: React.ReactNode;
  value: Activity;
}
export const ActivityProvider: React.FC<ActivityProviderProps> = ({
  children,
  value,
}) => (
  <ActivityContext.Provider value={useMemoDeep(value)}>
    {children}
  </ActivityContext.Provider>
);

// integrations/solid/src/__internal__/activity/ActivityProvider.tsx
import type { Activity } from "@stackflow/core";
import type { Accessor, Component, JSXElement } from "solid-js";
import { createContext } from "solid-js";

export const ActivityContext = createContext<Accessor<Activity | undefined>>(
  () => undefined,
);

interface ActivityProviderProps {
  children: JSXElement;
  value: Activity;
}
export const ActivityProvider: Component<ActivityProviderProps> = (props) => (
  <ActivityContext.Provider value={() => props.value}>
    {props.children}
  </ActivityContext.Provider>
);
