// integrations/react/src/activity/useActivityParams.ts
import { ActivityParams } from "@stackflow/core";
import { useContext } from "react";

import { ActivityContext } from "./ActivityContext";

/**
 * Get current activity parameters
 */
export function useActivityParams<
  T extends ActivityParams<T> = ActivityParams,
>(): T {
  return useContext(ActivityContext).params as any;
}

// integrations/solid/src/__internal__/activity/useActivityParams.ts
import type { Accessor } from "solid-js";
import { createMemo, useContext } from "solid-js";

import { ActivityContext } from "./ActivityProvider";

/**
 * Get current activity parameters
 */
export function useActivityParams<
  T extends { [key in keyof T]: string | undefined },
>(): Accessor<T | undefined> {
  const activity = useContext(ActivityContext);
  return createMemo(() => activity()?.params as T | undefined);
}
