// extensions/plugin-preload/src/react/LoadersContext.tsx
import { createContext, useContext } from "react";

import type { LoadersMap } from "../common/Loader";

export const LoadersContext = createContext<LoadersMap>({});

interface LoadersProviderProps {
  loaders: LoadersMap;
  children: React.ReactNode;
}
export const LoadersProvider: React.FC<LoadersProviderProps> = (props) => (
  <LoadersContext.Provider value={props.loaders}>
    {props.children}
  </LoadersContext.Provider>
);

LoadersProvider.displayName = "LoadersProvider";

export function useLoaders() {
  return useContext(LoadersContext);
}

// extensions/plugin-preload/src/solid/LoadersContext.solid.tsx
/* @jsxImportSource solid-js */

import {
  type Component,
  type JSXElement,
  createContext,
  useContext,
} from "solid-js";

import type { LoadersMap } from "../common/Loader";

export const LoadersContext = createContext<() => LoadersMap>(() => ({}));

interface LoadersProviderProps {
  loaders: LoadersMap;
  children: JSXElement;
}
export const LoadersProvider: Component<LoadersProviderProps> = (props) => (
  <LoadersContext.Provider value={() => props.loaders}>
    {props.children}
  </LoadersContext.Provider>
);

export function useLoaders() {
  return useContext(LoadersContext);
}
