// integrations/react/src/future/useActivityParams.ts
import { useContext } from "react";

import type {
  InferActivityParams,
  RegisteredActivityParamTypes,
} from "@stackflow/config";
import { ActivityContext } from "../__internal__/activity/ActivityProvider";

export function useActivityParams<
  ActivityName extends Extract<keyof RegisteredActivityParamTypes, string>,
>(): InferActivityParams<ActivityName> {
  return useContext(ActivityContext)
    .params as InferActivityParams<ActivityName>;
}

// integrations/solid/src/future/useActivityParams.ts
import type {
  InferActivityParams,
  RegisteredActivityParamTypes,
} from "@stackflow/config";
import { type Accessor, useContext } from "solid-js";
import { ActivityContext } from "../__internal__/activity/ActivityProvider";

export function useActivityParams<
  ActivityName extends Extract<keyof RegisteredActivityParamTypes, string>,
>(): Accessor<InferActivityParams<ActivityName>> {
  const activity = useContext(ActivityContext);
  return () => activity()?.params as InferActivityParams<ActivityName>;
}
